version: '3.3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      TZ: 'Asia/Tokyo'
      PGTZ: 'Asia/Tokyo'
    ports:
      - 5432:5432

